import "@/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next 13",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-teal-500 flex flex-col items-center justify-center">
          <h1 className="text-lg">Layout Comum Novo</h1>
        </div>
        {children}
      </body>
    </html>
  );
}
